Factory/Models/Engineer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }
    [Required(ErrorMessage = "The Engineers Name can't be blank")]
    public string EngineerName { get; set; }
    [Required(ErrorMessage = "The hire date must be added")]
    public string HireDate { get; set; }
    [Required(ErrorMessage = "You must add the Engineer License")]
    public string EngineerLicense { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public Engineer Engineer { get; set; }
    public int MachineId { get; set; }
    public Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachines { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    [Required(ErrorMessage = "You must add the Machines Name")]
    public string MachineName { get; set; }
    [Required(ErrorMessage = "You must add the install date")]
    public string InstallDate { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineerController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Models
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers.Include(engineer => engineer.JoinEntities).ThenInclude(join => join.Machine).FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
      else
      {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
      }
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
      #nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    private readonly FactoryContext _db;

    public HomeController(FactoryContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      Engineer[] engineer = _db.Engineers.ToArray();
      Machine[] machine = _db.Machines.ToArray();
      Dictionary<string,object[]> model = new Dictionary<string, object[]>();
      model.Add("engineers", engineer);
      model.Add("machines", machine);
      return View(model);
    }
  }
}

Factory/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Models
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines.Include(machine => machine.JoinEntities).ThenInclude(join => join.Engineer).FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if(!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
      }
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
      #nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineer/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>

<h4>Add a Machine to this Engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Selete Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Engineer list", "Index")</p>

Factory/Views/Engineer/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)</h3>

@if(@Model.JointEntities.Count == 0)
{
  <p>This Engineer does not have any Machines assigned to it</p>
}
else
{
  <h4>Machines the Engineer repairs:</h4>
  <ul>
    @foreach(EngineerMachine join in Model.JointEntities)
    {
      <li>@join.Machine.MachineName</li>
      @using (Html.BeginForm("DeleteJoin", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to Engineer list", "Index")</p>
<p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Edit Engineer Details", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>

<h4>Add a Machine to this Engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Selete Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Engineer list", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new Engineer</h4>

<p>@Html.ValidationMessageFor(model => model.EngineerName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.EngineerLicense, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName)
  @Html.EditorFor(model => model.EngineerName)
  @Html.LabelFor(model => model.HireDate)
  @Html.EditorFor(model => model.HireDate)
  @Html.LabelFor(model => model.EngineerLicense)
  @Html.EditorFor(model => model.EngineerLicense)

  <input type="submit" value="Add new Engineer" class="btn btn-default" />
}

<p>@Html.ActionLink("See list of Engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this Engineer?</h2>

@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Return to Engineer list", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Engineer does not have any Machines assigned to it</p>
}
else
{
  <h4>Machines the Engineer repairs:</h4>
  <ul>
    @foreach(EngineerMachine join in Model.JoinEntities)
    {
      <li>@join.Machine.MachineName</li>
      @using (Html.BeginForm("DeleteJoin", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to Engineer list", "Index")</p>
<p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Edit Engineer Details", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Edit this Engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.EngineerName)
  @Html.EditorFor(model => model.EngineerName)
  @Html.LabelFor(model => model.HireDate)
  @Html.EditorFor(model => model.HireDate)
  @Html.LabelFor(model => model.EngineerLicense)
  @Html.EditorFor(model => model.EngineerLicense)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Engineer list", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
 Layout = "_Layout";
}

@using Factory.Models

<h1>Engineers</h1>

@if (Model.Count == 0)
{
  <h3>No Engineers have been added yet</h3>
}

@foreach (Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId })</li>
}

<p>@Html.ActionLink("Add new Engineer", "Create")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

Factory/Views/Home/Index.cshtml
@{
 Layout = "_Layout";
}

@using Factory.Models

<h1>Welcome Sillystringz Factory Managment</h1>

<p>@Html.ActionLink("See all Engineers", "Index", "Engineers")</p>

<hr/>

@foreach (Engineer engineer in Model["engineers"])
{
  <li>@Html.ActionLink(@engineer.EngineerName, "Details", "Engineers", new { id = engineer.EngineerId })</li>
}

<hr/>

<p>@Html.ActionLink("See all Machines", "Index", "Machines")</p>

<hr/>

@foreach (Machine machine in Model["machines"])
{
  <li>@Html.ActionLink(@machine.MachineName, "Deatils", "Machines", new {id = machine.MachineId })</li>
}

Factory/Views/Machine/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Engineer</h2>

<h4>Add an Engineer to this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Selete Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Machine list", "Index")</p>

Factory/Views/Machine/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>

@using (BeginForm())
{
  @Html.LabelFor(model => model.MachineName)
  @Html.EditorFor(model => model.MachineName)
  @Html.LabelFor(model => model.InstallDate)
  @Html.EditorFor(model => model.InstallDate)

  <input type="submit" value="Add new Machine" class="btn btn-default" />
}

<p>@Html.ActionLink("See list of Machines", "Index")</p>

Factory/Views/Machine/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h3>

@if(@Model.JointEntities.Count == 0)
{
  <p>This Machine does not have any Engineers assigned to it</p>
}
else
{
  <h4>Engineers the Machine belongs to:</h4>
  <ul>
    @foreach(EngineerMachine join in Model.JointEntities)
    {
      <li>@join.Engineer.EngineerName</li>
      @using (Html.BeginForm("DeleteJoin", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to Machine list", "Index")</p>
<p>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Edit Machine Details", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Engineer</h2>

<h4>Add an Engineer to this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Selete Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Machine list", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>

<p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.InstallDate, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName)
  @Html.EditorFor(model => model.MachineName)
  @Html.LabelFor(model => model.InstallDate)
  @Html.EditorFor(model => model.InstallDate)

  <input type="submit" value="Add new Machine" class="btn btn-default" />
}

<p>@Html.ActionLink("See list of Machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this Machine?</h2>

@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Return to Machine list", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Machine does not have any Engineers assigned to it</p>
}
else
{
  <h4>Engineers the Machine belongs to:</h4>
  <ul>
    @foreach(EngineerMachine join in Model.JoinEntities)
    {
      <li>@join.Engineer.EngineerName</li>
      @using (Html.BeginForm("DeleteJoin", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to Machine list", "Index")</p>
<p>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Edit Machine Details", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Edit this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.MachineName)
  @Html.EditorFor(model => model.MachineName)
  @Html.LabelFor(model => model.InstallDate)
  @Html.EditorFor(model => model.InstallDate)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Machine list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
 Layout = "_Layout";
}

@using Factory.Models

<h1>Machines</h1>

@if (Model.Count == 0)
{
  <h3>No machines have been added yet</h3>
}

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
}

<p>@Html.ActionLink("Add new Machine", "Create")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sillystringz's Factory</title>
    <link 
      rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>